Repository DeveloperAcademy-POSTECH/MC3-Team13-RUN, pull requests merged in 2023-07, with the labels that each got.

#4 Feature/2 search music
  MoRI/MoRI.xcodeproj/project.pbxproj
  MoRI/MoRI/ContentView.swift
  MoRI/MoRI/Extension/Color+Extension.swift
  MoRI/MoRI/Extension/View+Extension.swift
  MoRI/MoRI/MoRIApp.swift
  MoRI/MoRI/Model/Song.swift
  MoRI/MoRI/VIew/MainView.swift
  MoRI/MoRI/VIew/SearchMusicView.swift
  MoRI/MoRI/VIew/SelectLyricsView.swift
  MoRI/MoRI/VIewModel/SearchMusicViewModel.swift
Labels: FEAT, GUI

#13 💄STYLE: #12 사라진 Fonts추가
  MoRI/MoRI.xcodeproj/project.pbxproj
  MoRI/MoRI/.DS_Store
  MoRI/MoRI/Fonts/FontsManager.swift
Labels: FIX

#34 Feature/#25 haptic effect
  MoRI/MoRI.xcodeproj/project.pbxproj
  MoRI/MoRI/VIew/ArchiveCardChipView.swift
  MoRI/MoRI/VIewModel/SearchMusicViewModel.swift
Labels: FEAT

#38 🛠️FIX: #37 merge시 발생하는 오류 해결
  MoRI/MoRI.xcodeproj/project.pbxproj
  MoRI/MoRI/VIew/ArchiveCardChipView.swift
Labels: ERROR, MERGE

#58 Fix/#21 search algorithm
  MoRI/MoRI/VIewModel/SearchMusicViewModel.swift
Labels: FIX

#71 💄GUI: #70 placeholder 사진 추가
  MoRI/MoRI/Assets.xcassets/placeholder.imageset/Contents.json
  MoRI/MoRI/Assets.xcassets/placeholder.imageset/Frame 48095723.svg
  MoRI/MoRI/VIew/SearchMusicView.swift
  MoRI/MoRI/VIew/SelectLyricsView.swift
Labels: GUI

#76 Fix/#74 delete dash
  MoRI/MoRI.xcodeproj/project.pbxproj
  MoRI/MoRI/Extension/Color+Extension.swift
  MoRI/MoRI/Extension/View+Extension.swift
  MoRI/MoRI/Model/Song.swift
  MoRI/MoRI/View/ArchiveCardChipView.swift
  MoRI/MoRI/View/AsyncImageView.swift
  MoRI/MoRI/View/CardDetail/CardDetailArt.swift
  MoRI/MoRI/View/CardDetail/CardDetailTop.swift
  MoRI/MoRI/View/CardDetail/CardDetailView.swift
  MoRI/MoRI/View/CompleteCard/CompleteCardTop.swift
  MoRI/MoRI/View/CompleteCard/CompleteCardView.swift
  MoRI/MoRI/View/EditCard/CardTop.swift
  MoRI/MoRI/View/EditCard/EditCardView.swift
  MoRI/MoRI/View/MainView.swift
  MoRI/MoRI/View/SearchMusicView.swift
  MoRI/MoRI/View/SelectLyricsView.swift
  MoRI/MoRI/ViewModel/CardDetailViewModel.swift
  MoRI/MoRI/ViewModel/CompleteCardViewModel.swift
  MoRI/MoRI/ViewModel/EditCardViewModel.swift
  MoRI/MoRI/ViewModel/SearchMusicViewModel.swift
  MoRI/MoRI/ViewModel/SelectLyricsViewModel.swift
Labels: GUI, FIX

#85 ♻️REFACTOR: #84 가수이름 ' / 노래제목 . 처리
  MoRI/MoRI.xcodeproj/project.pbxproj
  MoRI/MoRI/ViewModel/SearchMusicViewModel.swift
Labels: FIX

#93 🛠️ FIX: 카드 영역 밖에서 카드 선택 불가
  MoRI/MoRI/View/ArchiveCardChipView.swift
Labels: FIX
